# baseURL = 'https://example.org/'
# languageCode = 'en-us'
# title = 'My New Hugo Site'
baseURL = "https://oussamabh242.github.io/opensourcerer/"
languageCode = "en-us"
title = "Open Sourcerer"
siteTitle = "OpenSourcerer"
theme = "terminal"


[params]
	siteTitle = "OpenSourcerer"
  contentTypeName = "posts"
  themeColor = "green"

[params.logo]
logoText = "Open Sourcerer"

[markup.highlight]
  noClasses = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[menu]

  [[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/posts/"
  weight = 2

  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 3
  #
  # [[menu.main]]
  #   identifier = "about"
  #   name = "About"
  #   url = "/about/"
  #   weight = 2


[caches]
  [caches.images]
    dir = ':cacheDir/images'
